services:
  backend:
    volumes:
      - ./backend/app/templates:/app/app/templates
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
